print(True or False)
print(True or True)
print(False or True)
print(True and True)
print(False and True)
print((True and False) or True)
print(8==2)
print(9==9)
print((9<0) or (8>2))
print((8>=0) or (2<=9))
# try to guess the outputs
